config/routes.rb
Rails.application.routes.draw do
  
  root "articles#index"


  # get '/signup' => 'user#new'
  # post '/users' => 'user#create'
  
  # get '/' => 'user#index'

  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # get '/logout' => 'sessions#destroy'
  
  get '/logout' => 'sessions#destroy'

  resources :users
  resources :sessions

  resources :articles do
    resources :comments
  end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end
# belongs_to :user

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article


  # belongs_to :user

end
# bin/rails g model add_references_to_Comment user:references

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/current.rb
class Current < ApplicationRecord
  attr_accessor :user
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  validates :username, presence: true, uniqueness: true, length: { in: 4..20 } 
  
  validates :email, presence: true, uniqueness: true
  validates :password , presence: true, length: { in: 6..12 }
  # validates :password_digest, presence: true, length: { in: 6..12 }

end
#   has_many :posts
# has_many :comments

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end
  
  # helper_method :current_user 
 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
      # unless current_user == @article.user
      #   redirect_back fallback_location: root_path, notice: 'User is not owner'
      # end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end
  # private
  #   def owner?
  #     unless current_user == @article.user
  #       redirect_back fallback_location: root_path, notice: 'User is not owner'
  #     end
  #   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def show
    @article = Article.find(params[:article_id])
  end 
  def create
    @article = Article.find(params[:article_id])

    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)

    # @postid = params[:id]
    # if @comment.save
    #   flash[:notice] = "comment created."
    #   redirect_to '/posts'
    # else
    #   flash[:error] = "Error creating comment."
    #   redirect_to '/posts'
    # end
  end

  def edit
    @article = Article.find(params[:article_id])
    
  end
  def update

    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])

    if @comment.update(comment_params) 
      redirect_to @article
    else
    render :edit
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: :see_other
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # def show
  #   @user = User.find_by(params[:id])
  # end

  def new
  end
  
  def create
    @user = User.find_by(username: params[:username])
    
    if @user.present? #&& @user.authenticate(params[:password])
      if @user.present? && User.find_by(password: params[:password])
      session[:user_id] = @user.id
      flash[:notice]="Login successful"
      redirect_to root_path
      end
    else 
      flash[:notice]= "Invalid Email or Password"
      redirect_to new_session_path
   
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice]="Logged Out"
    redirect_to root_path
  end
  # def create
#   @user = User.find_by(username: params[:username])
#   @pass = User.find_by(password: params[:password])
  
#   if @user.present? && @pass.present? #&& @user.authenticate(params[:password])
#     session[:user_id] = @user.id
#     flash[:notice]="Login successful"
#     redirect_to root_path
#   else 
#     flash[:notice]= "Invalid Email or Password"
#     redirect_to new_session_path
 
#   end
# end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(users_params_data)
    if @user.save
      redirect_to new_session_path  :notice => "Registration Succesfull - Now Login ."
    else
      render  :new, status: :unprocessable_entity
    end
  end

  #  def XZY
  #   @user = User.find(login_params_data)
  #   if @user.id
  #     redirect_to root_path  :notice => "Registration Succesfull - Now Login ."
  #   else
  #     flash.now[:alert] = "Email or password is invalid"
  #     render :new, status: :unprocessable_entity
  #   end
  # end
  

  private
  def users_params_data
    params.require(:user).permit(:username, :email, :name, :dob, :password, :password_digest)
  end
  # private
  # def login_params_data
  #   params.require(:user).permit(:username,:password)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def current_user
  #   User.find(session[:user_id])
  # end
  def owner?(object)
    current_user == object.user 
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def current_user
        if session[:user_id]
            User.find(session[:user_id])
        end
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>----------------------------Welcome----------------------------</h1>
<h3>Articles List Show</h3>
Our blog has <%= Article.public_count %> articles and counting!
<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, article %>
      </li>
    <% end %>
  <% end %>
</ul>

<% if current_user.present?; %>
<%= link_to "Create New Article", new_article_path %>

<%end%>
<br>
<br>
<br>


<% if current_user %>
  <strong><%= link_to "LogOut", 'logout'  %></strong><br>

<% else %>
  <strong><%= link_to "Session Timeout - login now", new_session_path %></strong><br>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1>Article Section</h1>
<h3><%= @article.title %></h3>

<p><%= @article.body %></p>


<% if current_user.present?; %>
  <ul>

      <li><%= link_to "Edit", edit_article_path(@article) %></li>
      <li><%= link_to "Destroy", article_path(@article), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                      } %>
      </li>
  </ul>
<%end%>

<h2>---------------------------Comments Section ---------------------------</h2>
<%= render @article.comments %>


<% if current_user.present?; %>
  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>
<%end%>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <% if current_user.present?; %>
      <li><%= link_to "Edit", edit_article_comment_path(@article) %></li>  

      <%= link_to "Destroy Comment", [comment.article, comment], data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
    <% end %>     
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model:  [ @article, @article.comments.build  ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= render "form", article: @article %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Userportal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= "Active Status : " %>
  <% if current_user.present? %>
    
  <strong><%= current_user&.name; %></strong>

    <%else%>
    <h1>Login & Registration Portal</h1>
    <%=  "Login Your Account - " %>

    <strong ><%= link_to "Plesre Login-  Click here", new_session_path  %></strong><br><br>

    <%=  "Create New Account - " %>
    <strong><%= link_to "Registration Now", new_user_path %></strong><br><br>

    <%end%>
  <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>User Information </h1>

<ul>
  <% @users.each do |user| %>
      <li>
      user - id - <strong><%= user.id %></strong>
      </li>
      <li>
       name - <%= user.name %>
      </li>
      <li>
      username -  <%= user.username %>
      </li>
      <li>
      email -  <%= user.email %>
      </li>
      <li>
      password -  <%= user.password %>
      </li></br> 
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>New Registration</h1>

<%= form_with model: @user do |fm| %>
  <div>
  <strong><%= fm.label :username, "Enter Username" %></strong><br>
    <%= fm.text_field :username %>  <br>
    
    <% @user.errors.full_messages_for(:username).each do |message| %>
      <div><%= message %></div>
    <% end %><br>
  </div>

  <div>
  <strong><%= fm.label :email, "Enter Email" %></strong><br>
    <%= fm.text_area :email %><br>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %><br>
  </div>

  <div>
  <strong><%= fm.label :name , "Enter Name "%></strong><br>
    <%= fm.text_area :name %><br>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %><br>
   
  </div>

  <div>
  <strong><%= fm.label "Enter Birth Year" %></strong><br>
    <%= fm.text_field :dob %><br>
         
  </div>
    <div>
    <strong><%= fm.label :password , "Enter Password" %></strong><br>
    <%= fm.password_field :password %><br>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %><br>
    
  </div>
  <div>
  <strong><%= fm.label :password_digest , "Again Enter Password" %></strong><br>
  <%= fm.password_field :password_digest %><br>
  <% @user.errors.full_messages_for(:password_digest).each do |message| %>
    <div><%= message %></div>
  <% end %><br>
</div>
 
  <div>
    <%= fm.submit "Registration Here"%>
  </div>

<% end %>